name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.9.1
  dart_openai:
    path: ../
  envied: ^1.1.1
  http: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  lints: ^5.1.1
  test: ^1.25.15
